s = open('weights.txt')
c = s.readlines()
d = "/".join(c)
d = d.replace('\n', "")
d = d.split("/")
d = sorted(d, key=lambda w: float(w.split()[1]), reverse=True)
team_1 = "\n".join(d[::2])
team_2 = "\n".join(d[1::2])
fi = open('team.txt', 'a')
fi.writelines(team_1 + "\n" + team_2)
fi.close()
s.close()
